### ISSUE TITLE
能否添加一个zeabur的部署方案。

### ISSUE THREAD

**Issue by billowssun** [ConnectAI-E/AutoGPT-Next-Web#105]
目前安装AutoGPT-Next-Web安装教程点击deploy可以安装，手动去vercel官网部署就不能正常安装，收到安装zeabur也不行，希望出一个方案，隔壁chatGPT-next-web以皆可以正常安装。辛苦大佬。

**Comment by LiuElric** [comment]
1、手动去vercel应该也是没问题呀，关于这个可以详细说明一下出错的位置
2、zeabur 我们放在todolist

**Comment by Dogtiti** [comment]
@NateCC0902

**Comment by billowssun** [comment]
> 1、手动去vercel应该也是没问题呀，关于这个可以详细说明一下出错的位置
> 
> 2、zeabur 我们放在todolist

手动按默认下一步的 其他和教程一致

**Comment by LiuElric** [comment]
@NateCC0902

**Comment by jaysonfraser** [comment]
我也出现了同样的问题
![image](https://github.com/Dogtiti/AutoGPT-Next-Web/assets/64569102/2492b233-5978-416c-a736-e54786d3ad71)
![image](https://github.com/Dogtiti/AutoGPT-Next-Web/assets/64569102/1867a9d8-12bc-4376-9c03-2d35db9ce126)

**Comment by Dogtiti** [comment]
@jaysonfraser 环境变量没有填，按照教程一步步再来一遍
