### ISSUE TITLE
api.openai.com  开了全局代理,浏览器能访问 ping超时,代码访问也超时

### ISSUE THREAD

**Issue by skyemin** [ConnectAI-E/AutoGPT-Next-Web#143]

**Comment by Dogtiti** [comment]
给点具体信息，在哪里访问？如何部署的

**Comment by skyemin** [comment]
> 给点具体信息，在哪里访问？如何部署的
本机ide里直接部署,开了全局代理  浏览器访问api.openai.com可以 ping api.openai.com超时,是节点的问题吗?

**Comment by Dogtiti** [comment]
以何种方式部署 docker 还是直接npm 运行？ 应该是网络问题 没有收到大面积反馈超时问题
