### ISSUE TITLE
网络搜索

### ISSUE THREAD

**Issue by seagullz4** [ConnectAI-E/AutoGPT-Next-Web#225]
这个NEXT_PUBLIC_WEB_SEARCH_的搜索还可以，我就弱弱的问一句能不能加一下Google的那个搜索，我记得有个跟你一样的国外项目，加的就是Google API Keys Configuration这个免费版好像是1000次每个月

**Comment by Dogtiti** [comment]
我们现在用的也是google的搜索 有很多种 只不过服务商不同 目前是1000次免费
你说的这个免费额度是多少？
