### ISSUE TITLE
无法检索初始任务数组

### ISSUE THREAD

**Issue by VectorZhao** [ConnectAI-E/AutoGPT-Next-Web#276]
### Please check that this issue hasn't been reported before
请检查之前没有报告过此问题

- [X] I searched previous [Bug Reports](https://github.com/Dogtiti/AutoGPT-Next-Web/issues?q=is%3Aissue+is%3Aopen+label%3Abug) didn't find any similar reports.我搜索了以前的 [Bug Reports](https://github.com/Dogtiti/AutoGPT-Next-Web/issues?q=is%3Aissue+is%3Aopen+label%3Abug) 没有找到任何类似的报告。

### Expected Behavior/预期行为

正常运行agent

### Current behaviour/当前行为

无法检索初始任务数组。请重试，更清晰地表达您的目标，或修订您的目标，使其符合我们模型运行的政策。正在关闭。

### Steps to reproduce/重现步骤

填写名称和goal，运行代理

### Which Operating Systems are you using?您使用的是哪种操作系统？

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Acknowledgements致谢

- [X] My issue title is concise, descriptive, and in title casing.我的问题标题简明扼要，具有描述性，并且使用标题框
- [X] I have searched the existing issues to make sure this bug has not been reported yet.我已经搜索了现有问题以确保尚未报告此错误。
- [X] I am using the latest version of AutoGPT-Next-Web.我使用的是最新版本的 AutoGPT-Next-Web
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.我已经为维护者提供了足够的信息来重现和诊断问题。

**Comment by VectorZhao** [comment]
# 部署环境
vercel


<img width="1211" alt="image" src="https://github.com/ConnectAI-E/AutoGPT-Next-Web/assets/16644993/715f76e8-d7f4-422e-8bd1-3758c9b22537">

**Comment by Sheffield0x0** [comment]
我也遇到了同样的问题。请问您是如何解决的？

**Comment by VectorZhao** [comment]
> 我也遇到了同样的问题。请问您是如何解决的？

没，也没人回答。后来就放弃了

**Comment by kid9547** [comment]
我也遇到了相同的问题，点击重新部署也没有好
