### ISSUE TITLE
在Cloudflare部署失败了

### ISSUE THREAD

**Issue by qingyuan0o0** [ConnectAI-E/AutoGPT-Next-Web#303]
### Please check that this issue hasn't been reported before
请检查之前没有报告过此问题

- [X] I searched previous [Bug Reports](https://github.com/Dogtiti/AutoGPT-Next-Web/issues?q=is%3Aissue+is%3Aopen+label%3Abug) didn't find any similar reports.我搜索了以前的 [Bug Reports](https://github.com/Dogtiti/AutoGPT-Next-Web/issues?q=is%3Aissue+is%3Aopen+label%3Abug) 没有找到任何类似的报告。

### Expected Behavior/预期行为

我认为根据https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/cloudflare-pages-cn.md 应该可以部署成功

### Current behaviour/当前行为

我设置了环境变量是STRIPE_SECRET_KEY 
但是报错提示依旧需要提供STRIPE_SECRET_KEY 
<html>
<body>

23:52:53.017 | * branch            edcbf26fc0f414248f7def7fe7e6d2466ed29151 -> FETCH_HEAD
-- | --
23:52:53.017 |  
23:52:53.231 | HEAD is now at edcbf26 Merge pull request #297 from ConnectAI-E/dependabot/npm_and_yarn/prettier-plugin-tailwindcss-0.5.4
23:52:53.232 |  
23:52:53.337 |  
23:52:53.367 | Success: Finished cloning repository files
23:52:54.018 | Detected the following tools from environment: npm@9.5.1, nodejs@18.16.1
23:52:54.019 | Installing project dependencies: npm clean-install --progress=false
23:53:04.018 | npm WARN deprecated @types/prettier@3.0.0: This is a stub types definition. prettier provides its own type definitions, so you do not need this installed.
23:53:19.854 |  
23:53:19.855 | > auto-gpt-next-web@1.0.0 postinstall
23:53:19.855 | > prisma generate
23:53:19.855 |  
23:53:20.615 | Prisma schema loaded from prisma/schema.prisma
23:53:21.211 |  
23:53:21.212 | ✔ Generated Prisma Client (v5.2.0) to ./node_modules/@prisma/client in 161ms
23:53:21.212 | Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
23:53:21.212 | ```
23:53:21.212 | import { PrismaClient } from '@prisma/client'
23:53:21.212 | const prisma = new PrismaClient()
23:53:21.212 | ```
23:53:21.213 | or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
23:53:21.213 | ```
23:53:21.213 | import { PrismaClient } from '@prisma/client/edge'
23:53:21.213 | const prisma = new PrismaClient()
23:53:21.213 | ```
23:53:21.213 |  
23:53:21.214 | See other ways of importing Prisma Client: http://pris.ly/d/importing-client
23:53:21.214 |  
23:53:21.269 |  
23:53:21.269 | > auto-gpt-next-web@1.0.0 prepare
23:53:21.269 | > husky install
23:53:21.270 |  
23:53:21.372 | husky - Git hooks installed
23:53:21.431 |  
23:53:21.431 | added 1144 packages, and audited 1145 packages in 26s
23:53:21.431 |  
23:53:21.431 | 270 packages are looking for funding
23:53:21.432 | run `npm fund` for details
23:53:21.437 |  
23:53:21.438 | 4 moderate severity vulnerabilities
23:53:21.438 |  
23:53:21.438 | To address all issues, run:
23:53:21.438 | npm audit fix
23:53:21.438 |  
23:53:21.438 | Run `npm audit` for details.
23:53:21.466 | Executing user command: npx @cloudflare/next-on-pages@1
23:53:23.929 | npm WARN exec The following package was not found and will be installed: @cloudflare/next-on-pages@1.6.0
23:53:30.658 | npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
23:53:30.777 | npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
23:53:34.949 | ⚡️ @cloudflare/next-on-pages CLI v.1.6.0
23:53:34.954 | ⚡️ Detected Package Manager: npm
23:53:34.954 | ⚡️ Preparing project...
23:53:34.954 | ⚡️ Project is ready
23:53:34.955 | ⚡️ Building project...
23:53:36.999 | ▲  npm
23:53:37.000 | ▲  WARN exec The following package was not found and will be installed: vercel@32.2.0
23:53:41.780 | ▲  Vercel CLI 32.2.0
23:53:42.120 | ▲  Warning: Detected "engines": { "node": ">=18.0.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
23:53:42.140 | ▲  Installing dependencies...
23:53:44.744 | ▲  > auto-gpt-next-web@1.0.0 postinstall
23:53:44.744 | ▲  > prisma generate
23:53:45.506 | ▲  Prisma schema loaded from prisma/schema.prisma
23:53:46.108 | ▲  ✔ Generated Prisma Client (v5.2.0) to ./node_modules/@prisma/client in 165ms
23:53:46.108 | ▲  Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
23:53:46.108 | ▲  ```
23:53:46.108 | ▲  import { PrismaClient } from '@prisma/client'
23:53:46.109 | ▲  const prisma = new PrismaClient()
23:53:46.109 | ▲  ```
23:53:46.109 | ▲  or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
23:53:46.109 | ▲  ```
23:53:46.109 | ▲  import { PrismaClient } from '@prisma/client/edge'
23:53:46.109 | ▲  const prisma = new PrismaClient()
23:53:46.110 | ▲  ```
23:53:46.110 | ▲
23:53:46.110 | ▲  See other ways of importing Prisma Client: http://pris.ly/d/importing-client
23:53:46.188 | ▲  > auto-gpt-next-web@1.0.0 prepare
23:53:46.189 | ▲  > husky install
23:53:46.318 | ▲  husky - Git hooks installed
23:53:46.338 | ▲  up to date in 3s
23:53:46.339 | ▲  270 packages are looking for funding
23:53:46.339 | ▲  run `npm fund` for details
23:53:46.354 | ▲  Detected Next.js version: 13.4.13
23:53:46.363 | ▲  Detected `package-lock.json` generated by npm 7+...
23:53:46.364 | ▲  Running "npm run build"
23:53:47.248 | ▲  > auto-gpt-next-web@1.0.0 build
23:53:47.248 | ▲  > next build --no-lint
23:53:47.817 | ▲  - warn Linting is disabled
23:53:48.019 | ▲  Attention: Next.js now collects completely anonymous telemetry regarding usage.
23:53:48.020 | ▲  This information is used to shape Next.js' roadmap and prioritize features.
23:53:48.020 | ▲  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
23:53:48.020 | ▲  https://nextjs.org/telemetry
23:53:48.136 | ▲  - info Checking validity of types...
23:53:55.708 | ▲  Failed to compile.
23:53:55.709 | ▲  ./src/pages/api/webhooks/stripe.ts:11:3
23:53:55.709 | ▲  Type error: Type '"2022-11-15"' is not assignable to type '"2023-08-16"'.
23:53:55.710 | ▲
23:53:55.710 | ▲     9 \|
23:53:55.710 | ▲    10 \| const stripe = new Stripe(env.STRIPE_SECRET_KEY ?? "", {
23:53:55.710 | ▲  > 11 \|   apiVersion: "2022-11-15",
23:53:55.710 | ▲       \|   ^
23:53:55.711 | ▲    12 \| });
23:53:55.711 | ▲    13 \|
23:53:55.711 | ▲    14 \| const webhookSecret = env.STRIPE_WEBHOOK_SECRET ?? "";
23:53:55.780 | ▲  Error: Command "npm run build" exited with 1
23:53:55.888 |  
23:53:55.888 | ⚡️ The Vercel build (`npx vercel build`) command failed. For more details see the Vercel logs above.
23:53:55.889 | ⚡️ If you need help solving the issue, refer to the Vercel or Next.js documentation or their repositories.
23:53:55.889 |  
23:53:55.933 | Failed: Error while executing user command. Exited with error code: 1
23:53:55.943 | Failed: build command exited with code: 1
23:53:56.794 | Failed: error occurred while running build command

</body>
</html>

### Steps to reproduce/重现步骤

重现步骤是根据https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/cloudflare-pages-cn.md操作

### Possible solution/可能的解决方案

修改next.config.mjs，在这里说明需要哪些环境变量？

### Which Operating Systems are you using?您使用的是哪种操作系统？

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements致谢

- [X] My issue title is concise, descriptive, and in title casing.我的问题标题简明扼要，具有描述性，并且使用标题框
- [X] I have searched the existing issues to make sure this bug has not been reported yet.我已经搜索了现有问题以确保尚未报告此错误。
- [X] I am using the latest version of AutoGPT-Next-Web.我使用的是最新版本的 AutoGPT-Next-Web
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.我已经为维护者提供了足够的信息来重现和诊断问题。

**Comment by Dogtiti** [comment]
找错地儿了～
